package app

import "github.com/fisker086/keyops/internal/api/router"

// RouterDeps builds router dependencies from application wiring.
func RouterDeps(h *Handlers, s *Services, repos *Repositories, mode string) router.Deps {
	return router.Deps{
		Mode: mode,
		Handlers: router.HandlerSet{
			Mcp:              h.Mcp,
			ApiKey:           h.ApiKey,
			Host:             h.Host,
			Dashboard:        h.Dashboard,
			Session:          h.Session,
			Proxy:            h.Proxy,
			Auth:             h.Auth,
			Blacklist:        h.Blacklist,
			Setting:          h.Setting,
			Routing:          h.Routing,
			Connection:       h.Connection,
			HostGroup:        h.HostGroup,
			Approval:         h.Approval,
			ApprovalCallback: h.ApprovalCallback,
			File:             h.File,
			AssetSync:        h.AssetSync,
			SystemUser:       h.SystemUser,
			Role:             h.Role,
			PermissionRule:   h.PermissionRule,
			TwoFactor:        h.TwoFactor,
			Permission:       h.Permission,
			FormTemplate:     h.FormTemplate,
			FormCategory:     h.FormCategory,
			Ticket:           h.Ticket,
			TicketDraft:      h.TicketDraft,
			Workflow:         h.Workflow,
			K8s:              h.K8s,
			K8sCluster:       h.K8sCluster,
			K8sPermission:    h.K8sPermission,
			K8sSearch:        h.K8sSearch,
			Deployment:       h.Deployment,
			Bill:             h.Bill,
			ExpensesMap:      h.ExpensesMap,
			CloudAccount:     h.CloudAccount,
			Resources:        h.Resources,
			BillDashboard:    h.BillDashboard,
			Monitor:          h.Monitor,
			Organization:     h.Organization,
			Application:      h.Application,
			AppDeployBinding: h.AppDeployBinding,
			Registry:         h.Registry,
			Jenkins:          h.Jenkins,
			Audit:            h.Audit,
			Alert:            h.Alert,
			OnCall:           h.OnCall,
			DMSInstance:      h.DMSInstance,
			DMSQuery:         h.DMSQuery,
			DMSQueryLog:      h.DMSQueryLog,
			DMSPermission:    h.DMSPermission,
			Release:          h.Release,
			BuildMaster:      h.BuildMaster,
			AiAssistant:      h.AiAssistant,
		},
		Services: router.ServiceSet{
			ApiKey:        s.ApiKey,
			Auth:          s.Auth,
			K8sPermission: s.K8sPermission,
		},
		RoleRepo: repos.Role,
	}
}
